### ISSUE TITLE
Fix QuickBlur on Windows 8 (also need to test Windows 10)

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#158]
PhotoDemon's QuickBlur function wraps GDI+ blur effects if available.

Unfortunately, GDI+ blurs have a bizarre bug on Windows 8, where any radius < 20 only blurs in the horizontal direction.  (https://msdn.microsoft.com/en-us/library/ms534057%28v=vs.85%29.aspx)  I found this out the hard way when testing new drop shadow code, aaarrrggghh.

I'm leaving this issue up until I have a chance to test on Windows 10, as it's possible the bug is fixed there.  Once I know that, I can set up an appropriate version check for falling back to PD-specific methods as necessary.

**Comment by Kroc** [comment]
Darn, just removed Windows 10 from my machine as it borked and wouldn't boot anymore. It's a huge improvement over Windows 8 but highly unstable at the moment.

**Comment by tannerhelland** [comment]
Urgh, that unstable, huh?  That probably means testing it right now wouldn't be indicative anyway, since GDI+ might change again between now and release.  Good to know.

The Windows graphics stack has always been sketchy, but GDI+ seems particularly prone to breaking between releases.  I have no idea how Microsoft engineers keep breaking it in new and exciting ways...

**Comment by tannerhelland** [comment]
Since it'll be awhile before we definitively know whether this is fixed in Windows 10, I'll just extend the Windows 8/8.1 logic to it for now.  GDI+ isn't much faster at those radii anyway, so it's not a big deal to fall back to our internal methods.

**Comment by Kroc** [comment]
Could just be my hardware, or the software I'm throwing at it, but Windows 10 is definitely at an "alpha" stage right now, much more so than previous Windows technical previews. Window borders are broken as they appear to be in the process of trying to wrangle a default border width of 1, but that isn't expected by the majority of software, especially older stuff.

**Comment by tannerhelland** [comment]
Just what I need, more window management nightmares!  (I kid, 1px borders might be a nice solution if they can make it workable.)

I'd also heard that current builds were leaking GDI objects like a sieve, which contributed to the random crashiness.  No idea if that's fixed with the January update.

**Comment by Lakritzator** [comment]
I reported that issue some time ago here:
https://social.technet.microsoft.com/Forums/windows/en-US/99ddbe9d-556d-475a-8bab-84e25aa13a2c/problems-with-gdi-blureffect-on-windows-8?forum=w8itprogeneral

Now, due to a bug in the Windows version detection, I was confronted with it again (https://greenshot.atlassian.net/browse/BUG-2093)

Anyway, I just wanted to report that the problem is still there in Windows 10.

**Comment by tannerhelland** [comment]
Hi Lakritzator.  Thank you for the update.  It is very frustrating that Microsoft hasn't fixed such a trivial bug.  (And frankly, it's frustrating that the bug was ever introduced in the first place.  Why don't they perform regression testing on their major graphics API?)

If I see any changes in the Win 10 Creators Update, I'll pass along a message, but at this point, I'm not very hopeful.
