### ISSUE TITLE
[BUG] - Opening the 8bf plugins dialog crashes the application

### ISSUE THREAD

**Issue by manfromarce** [tannerhelland/PhotoDemon#716]
### Version information

- PhotoDemon version: PhotoDemon 2025.4 alfa (build 158)
- Windows 11 25H2 (build 26200.7171)

### How can I reproduce the bug?

I don't know if this depend on some specific configuration I have but opening the 8bf plugins dialog crashes the application for me.  

Behavior: 
- I go to Effects > Photoshop 8bf plugins.
- The window is displayed briefly, then PhotoDemon closes abruptly, so maybe something goes wrong when enumerating plugins (?)

The behavior is the same with different images, or if the 8bf plugins directory is empty or contains different plugins.

### Expected behavior

The dialog should of course load plugins properly and not crash.

### Debug logs

I have attached the debug log but it doesn't contain any specific error on this.

[DebugReport_0.log](https://github.com/user-attachments/files/23560975/DebugReport_0.log)

**Comment by opsimathic** [comment]
Hello Tanner - thanks for including me in this conversation - much
appreciated.

I have little to add except to confirm the crashes occur with an empty
Data\8bfPlugins folder.

Both App\plugins\PhotoDemon\Plugins and Data\PluginData folders have a ton
of files I don't recognize, but I assume that is correct as I am working
with a fresh copy of PhotoDemon.

Sorry I am unable to help more than this.

*/John*

John Cassels
32 Thornbush Crescent, Waterloo ON, N2T 1B2 Canada
***@***.***
+1-226-978-9506

**Comment by opsimathic** [comment]
Thank you for this update - much appreciated.

*/John*

John Cassels
32 Thornbush Crescent, Waterloo ON, N2T 1B2 Canada
***@***.***
+1-226-978-9506

**Comment by tannerhelland** [comment]
Please don't apologize, @manfromarce .  I am very grateful that you reported this problem!  I just wish I had a faster and easier solution for it.

As usual, what began as a small fix has now turned into a much larger project.  I am slowly working on removing the 3rd-party library that currently handles Photoshop plugins for PhotoDemon, and instead, I am replacing its features with my own code.  

I have just merged a first "wave" of changes into nightly builds.  PhotoDemon now has its own code for scanning for 8bf plugins, validating the ones it finds, and displaying its discoveries to the user.  This *should* fix any problems related to just opening the 8bf plugins dialog.

If you actually *launch* an 8bf plugin, that is still handled by a 3rd-party library.  I will work on replacing this in the coming weeks.

Please let me know if you still experience crashes when opening the 8bf dialog, and thank you for your patience while I worked on this!

**Comment by opsimathic** [comment]
With great regret, I report that PhotoDemon still crashes during the 8bf
plugin load dialogue - directory data/8bfPlugins is empty - I am using
build 2026.1 alpha (build 58) on Win 11 home 64 bit.  Am I doing something
wrong?

*/John*

John Cassels
32 Thornbush Crescent, Waterloo ON, N2T 1B2 Canada
***@***.***
+1-226-978-9506
